FROM python:3.13.7-slim-bookworm

WORKDIR /app/

COPY ./requirements.txt .

# RUN apt update && apt upgrade && apt install curl build-essentials

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

