# Generated by Django 5.2.6 on 2025-09-14 17:26

import autoslug.fields
import django.utils.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=django.utils.text.slugify, unique=True),
        ),
    ]
